### PR TITLE
Connect from Runtime Manager to Veracruz Server instead of other way.

### LINKED ISSUE #565: Linux Runtime Manager panics printing to stdout
**Describe the bug**
On Linux, the Runtime Manager panics printing to stdout:
```
thread 'main' panicked at 'failed printing to stdout: Broken pipe (os error 32)', library/std/src/io/stdio.rs:1164:9
```
~~Incidentally, this results in Veracruz-Server's CPU usage spiking to 100%~~ (fixed in #567) 
This happens because VC-Server is using `stdout` to sync with RM, then destroys the pipe after sync, resulting in subsequent writes to `stdout` to fail.

**To Reproduce**
Add a `println!` to any dependency of the RM, e.g. in `execution-engine/src/fs.rs`.
Recompile and run Veracruz end-to-end.

**Expected behaviour**
The Runtime Manager shouldn't fail, let alone panic.

**Possible solutions**
1. As a workaround, `eprintln!` should be used for debugging instead of `println!`, however we don't have much control over what native modules do. For example, TensorFlow Lite, used by the TensorFlow inference native module, prints all sorts of stuff to `stdout`
2. Use a named pipe for the sync channel to avoid interfering with standard streams
3. Redirect `stdout` "back to itself" (or `/dev/null` in release mode?) after the pipe is destroyed on the VC-Server side. Is this possible on IceCap?

### PR DESCRIPTION
**Pull request by egrimley-arm**
Only on Linux, for now. This probably fixed #565.

For reviewing this you might want to look at the separate commits as there is a commit that changes indentation.

### CODE REVIEW

**Review by dreemkiller — COMMENTED** [review]
So, this works, then?

**Comment by egrimley-arm** [comment]
> What are the changes in nitro for, then?

There's a separate commit that removes some unused functions.

**Comment by egrimley-arm** [comment]
This could be three separate tiny PRs, I suppose.

**Review by dreemkiller — APPROVED** [review]

File: veracruz-server/src/common.rs [hunk 1]
```diff
@@ -104,21 +103,12 @@ pub trait VeracruzServer {
...
-    fn close_tls_session(&mut self, session_id: u32) -> VeracruzServerResult<()>;
-
     // The first bool indicates if the enclave is active, and the second vec contains the response
     fn tls_data(
         &mut self,
         session_id: u32,
         input: Vec<u8>,
     ) -> VeracruzServerResult<(bool, Option<Vec<Vec<u8>>>)>;
-
-    fn shutdown_isolate(&mut self) -> Result<(), Box<dyn Error>>;
```
Comment (gbryant-arm) [inline veracruz-server/src/common.rs:123]: Why was this moved outside of the `VeracruzServer` trait? Shouldn't `shutdown_isolate()` be implemented for every target?

**Review by gbryant-arm — COMMENTED** [review]
Looks good. Is the reason for not implementing this for IceCap and Nitro too, making the PR smaller? Are you hopeful that the same thing can be implemented on those targets?

File: runtime-manager/src/platforms/linux.rs [hunk 2]
```diff
@@ -201,29 +197,19 @@ pub fn linux_main() -> Result<()> {
...
-        error!("Did not receive any port to listen on.  Exiting...");
+        error!("No address given. Exiting...");
         return Err(anyhow!(RuntimeManagerError::CommandLineArguments));
     };
 
     let measurement = if let Some(measurement) = matches.value_of("runtime_manager_measurement") {
-        info!(
-            "Received {} as Runtime Manager enclave measurement.",
-            measurement
-        );
```
[the remark this answers is not in the document]
Comment (egrimley-arm) [reply runtime-manager/src/platforms/linux.rs:223]: It just seemed unnecessary, and I wasn't adding anything for the other command-line option.

File: veracruz-server/src/common.rs (hunk 1 above)
Comment (egrimley-arm) [reply veracruz-server/src/common.rs:123]: It's implemented, but it's not in the API any more because the shutdown is initated by dropping the struct: https://github.com/veracruz-project/veracruz/blob/2682973574a1424352f8905a6b74b470a36f4145/veracruz-server/src/server.rs#L61
